# Generated by Django 4.2.13 on 2024-06-10 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('power_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('power_rating', models.PositiveIntegerField(default=1, help_text='Power rating in watts')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_items', to='power_calculator.appliance')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculations.calculation')),
            ],
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['-created'], name='calculation_created_a51192_idx'),
        ),
    ]
