# Generated by Django 4.2.13 on 2025-01-09 18:39

from django.db import migrations, models
import django.db.models.deletion
import power_calculator.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Appliances',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_load', models.FloatField(default=0, editable=False)),
                ('inverter_rating', models.FloatField(default=0, editable=False)),
                ('backup_time', models.PositiveIntegerField(default=2, help_text='How many hours of backup you need during a power outage.', validators=[power_calculator.validators.validate_backup_time])),
                ('battery_capacity', models.PositiveIntegerField(choices=[(150, '150Ah 12V'), (200, '200Ah 12V'), (220, '220Ah 12V'), (250, '250Ah 12V')], default=150, validators=[power_calculator.validators.validate_battery_capacity])),
                ('system_voltage', models.PositiveIntegerField(choices=[(12, '12V'), (24, '24V'), (48, '48V')], default=0)),
                ('total_battery_capacity', models.FloatField(default=0, editable=False)),
                ('numbers_of_batteries', models.PositiveIntegerField(default=0, editable=False)),
                ('total_solar_panel_capacity_needed', models.FloatField(default=0, editable=False)),
                ('solar_panel_watt', models.PositiveIntegerField(choices=[(300, '300W'), (350, '350W'), (400, '400W'), (450, '450W')], default=300)),
                ('numbers_of_solar_panel', models.IntegerField(default=0, editable=False)),
                ('total_current', models.FloatField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Calculations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('power_rating', models.PositiveIntegerField(default=1, validators=[power_calculator.validators.validate_power_rating])),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='power_calculator.appliance')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc', to='power_calculator.calculation')),
            ],
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['-created'], name='power_calcu_created_6670b6_idx'),
        ),
        migrations.AddIndex(
            model_name='appliance',
            index=models.Index(fields=['-created'], name='power_calcu_created_49cfa1_idx'),
        ),
    ]
