# Generated by Django 4.1.13 on 2024-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Numbers of appliance')),
                ('power_rating', models.PositiveIntegerField(help_text='Power rating in watts')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AddIndex(
            model_name='appliance',
            index=models.Index(fields=['-updated'], name='power_calcu_updated_283a20_idx'),
        ),
    ]
