# Generated by Django 4.2.2 on 2024-06-11 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_power_needed', models.FloatField()),
                ('inverter_power', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Appliance',
        ),
    ]
