# Generated by Django 4.2.13 on 2024-06-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0002_calculation_delete_appliance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculation',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Calculations'},
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='calculation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['-created'], name='power_calcu_created_6670b6_idx'),
        ),
    ]
