# Generated by Django 4.2.13 on 2024-06-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0003_alter_calculation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='backup_time',
            field=models.BigIntegerField(default=2, help_text='How many hours of backup you need during a power outage.'),
        ),
    ]
