# Generated by Django 4.2.13 on 2024-06-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0004_calculation_backup_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='inverter_power',
            new_name='inverter_rating',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='total_power_needed',
            new_name='total_load',
        ),
    ]
