# Generated by Django 4.2.13 on 2024-06-12 08:25

from django.db import migrations, models
import power_calculator.models


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0005_rename_inverter_power_calculation_inverter_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='battery_capacity',
            field=models.BigIntegerField(default=150, validators=[power_calculator.models.validate_battery_capacity]),
        ),
    ]
