# Generated by Django 4.2.13 on 2024-06-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0006_calculation_battery_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Numbers of appliance')),
                ('power_rating', models.PositiveIntegerField(help_text='Power rating in watts')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Appliances',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='power_calcu_created_49cfa1_idx'), models.Index(fields=['id'], name='power_calcu_id_72e218_idx')],
            },
        ),
    ]
