# Generated by Django 4.2.13 on 2024-06-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0007_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='appliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_items', to='power_calculator.appliance'),
        ),
    ]
