# Generated by Django 4.2.13 on 2024-06-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0009_calculationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='backup_time',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='inverter_rating',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='total_load',
        ),
    ]
