# Generated by Django 4.2.13 on 2024-06-12 19:08

from django.db import migrations, models
import power_calculator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0010_remove_calculation_backup_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationitem',
            name='backup_time',
        ),
        migrations.RemoveField(
            model_name='calculationitem',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='calculationitem',
            name='inverter_rating',
        ),
        migrations.RemoveField(
            model_name='calculationitem',
            name='total_load',
        ),
        migrations.AddField(
            model_name='calculation',
            name='backup_time',
            field=models.BigIntegerField(default=2, help_text='How many hours of backup you need during a power outage.'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='battery_capacity',
            field=models.BigIntegerField(default=150, validators=[power_calculator.validators.validate_battery_capacity]),
        ),
        migrations.AddField(
            model_name='calculation',
            name='inverter_rating',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='calculation',
            name='total_load',
            field=models.FloatField(default=1),
        ),
    ]
