# Generated by Django 4.2.13 on 2024-06-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0011_remove_calculationitem_backup_time_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appliance',
            name='power_calcu_id_72e218_idx',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='appliance',
        ),
    ]
