# Generated by Django 4.2.13 on 2024-06-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0012_remove_appliance_power_calcu_id_72e218_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='power_rating',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='quantity',
        ),
        migrations.AddField(
            model_name='calculationitem',
            name='power_rating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='calculationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='inverter_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='total_load',
            field=models.FloatField(default=0),
        ),
    ]
