# Generated by Django 4.2.13 on 2024-06-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0013_remove_appliance_power_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='battery_voltage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='numbers_of_batteries',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='numbers_of_solar_panel',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='total_battery_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='total_current',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='total_solar_panel_capacity',
            field=models.FloatField(default=0),
        ),
    ]
