# Generated by Django 4.2.13 on 2024-06-13 08:53

from django.db import migrations, models
import power_calculator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0014_calculation_battery_voltage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='battery_voltage',
            field=models.IntegerField(choices=[(12, '12V'), (24, '24V'), (48, '48V')], default=0),
        ),
        migrations.AlterField(
            model_name='calculationitem',
            name='power_rating',
            field=models.PositiveIntegerField(default=1, validators=[power_calculator.validators.validate_power_rating]),
        ),
    ]
