# Generated by Django 4.2.13 on 2024-06-13 10:01

from django.db import migrations, models
import power_calculator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0015_alter_calculation_battery_voltage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='solar_panel_watt',
            field=models.IntegerField(choices=[(300, '300W'), (350, '350W'), (400, '400W'), (450, '450W')], default=300),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='battery_capacity',
            field=models.BigIntegerField(choices=[(150, '150Ah'), (200, '200Ah'), (220, '220Ah'), (250, '250Ah')], default=150, validators=[power_calculator.validators.validate_battery_capacity]),
        ),
    ]
