# Generated by Django 4.2.13 on 2024-06-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0016_calculation_solar_panel_watt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='inverter_rating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='numbers_of_batteries',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='numbers_of_solar_panel',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='total_battery_capacity',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='total_current',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='total_load',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='total_solar_panel_capacity',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
