# Generated by Django 4.2.13 on 2024-06-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0017_alter_calculation_inverter_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='total_solar_panel_capacity',
            new_name='total_solar_panel_capacity_needed',
        ),
    ]
