# Generated by Django 4.2.13 on 2024-06-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0018_rename_total_solar_panel_capacity_calculation_total_solar_panel_capacity_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='numbers_of_solar_panel',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
