# Generated by Django 4.2.13 on 2024-06-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0019_alter_calculation_numbers_of_solar_panel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='battery_voltage',
            new_name='system_voltage',
        ),
    ]
