# Generated by Django 4.2.13 on 2024-06-18 10:19

from django.db import migrations, models
import power_calculator.validator


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0020_rename_battery_voltage_calculation_system_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='battery_capacity',
            field=models.BigIntegerField(choices=[(150, '150Ah 12V'), (200, '200Ah 12V'), (220, '220Ah 12V'), (250, '250Ah 12V')], default=150, validators=[power_calculator.validator.validate_battery_capacity]),
        ),
    ]
