# Generated by Django 4.2.13 on 2024-06-22 11:09

from django.db import migrations, models
import power_calculator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0021_alter_calculation_battery_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='backup_time',
            field=models.PositiveIntegerField(default=2, help_text='How many hours of backup you need during a power outage.', validators=[power_calculator.validators.validate_backup_time]),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='battery_capacity',
            field=models.PositiveIntegerField(choices=[(150, '150Ah 12V'), (200, '200Ah 12V'), (220, '220Ah 12V'), (250, '250Ah 12V')], default=150, validators=[power_calculator.validators.validate_battery_capacity]),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='numbers_of_batteries',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='solar_panel_watt',
            field=models.PositiveIntegerField(choices=[(300, '300W'), (350, '350W'), (400, '400W'), (450, '450W')], default=300),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='system_voltage',
            field=models.PositiveIntegerField(choices=[(12, '12V'), (24, '24V'), (48, '48V')], default=0),
        ),
    ]
