# Generated by Django 4.2.13 on 2024-12-07 12:16

from django.db import migrations, models
import django.db.models.deletion
import inverter_rating_v2.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('power_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_voltage', models.PositiveIntegerField(choices=[(12, '12V'), (24, '24V'), (48, '48V')], default=0)),
                ('battery_capacity', models.PositiveIntegerField(choices=[(150, '150Ah 12V'), (200, '200Ah 12V'), (220, '220Ah 12V'), (250, '250Ah 12V')], default=150, validators=[inverter_rating_v2.validators.validate_battery_capacity])),
                ('solar_panel_watt', models.PositiveIntegerField(choices=[(300, '300W'), (350, '350W'), (400, '400W'), (450, '450W')], default=300)),
                ('total_load', models.FloatField(default=0, editable=False)),
                ('inverter_rating', models.FloatField(default=0, editable=False)),
                ('total_battery_capacity', models.FloatField(default=0, editable=False)),
                ('numbers_of_solar_panel', models.IntegerField(default=0, editable=False)),
                ('controller_current', models.IntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Calculations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('power_rating', models.PositiveIntegerField(default=0, validators=[inverter_rating_v2.validators.validate_power_rating])),
                ('backup_time', models.PositiveIntegerField(default=0, validators=[inverter_rating_v2.validators.validate_backup_time])),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliance', to='power_calculator.appliance')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_calc', to='inverter_rating_v2.calculation')),
            ],
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['-created'], name='inverter_ra_created_241bdd_idx'),
        ),
    ]
