# Generated by Django 4.2.13 on 2024-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverter_rating_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='numbers_of_batteries',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='calculation',
            name='total_solar_panel_capacity_needed',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
