# Generated by Django 5.2.17 on 2026-09-23 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inverter_rating_v2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculationitem",
            name="calculation",
        ),
        migrations.RemoveField(
            model_name="calculationitem",
            name="appliance",
        ),
        migrations.DeleteModel(
            name="Calculation",
        ),
        migrations.DeleteModel(
            name="CalculationItem",
        ),
    ]
