# Generated by Django 4.2.13 on 2024-12-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inverter_rating_v2', '0002_calculation_numbers_of_batteries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationitem',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_calc', to='inverter_rating_v2.calculation'),
        ),
    ]
