# Generated by Django 4.2.13 on 2024-12-07 13:16

from django.db import migrations, models
import inverter_rating_v2.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inverter_rating_v2', '0003_alter_calculationitem_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationitem',
            name='backup_time',
            field=models.FloatField(default=0, validators=[inverter_rating_v2.validators.validate_backup_time]),
        ),
    ]
